const searchQueryProgrammingLanguage = [
	"Python",
	"JavaScript",
	"TypeScript",
	"C++",
	"C",
	"Go",
	"C#",
	"Shell",
	"Rust",
	"Java",
	"HTML",
	"PHP",
	"Ruby",
	"Lua",
	"Jupyter Notebook",
	"Kotlin",
	"Swift",
	"CSS",
	"Emacs Lisp",
	"Vim Script",
	"Dart",
	"SCSS",
	"PowerShell",
	"Haskell",
	"Vue",
	"Scala",
	"Perl",
	"R",
	"Solidity",
	"Clojure",
	"Makefile",
	"Batchfile",
	"Svelte",
	"Dockerfile",
	"Objective-C",
	"TeX",
	"Common Lisp",
	"GDScript",
	"Nix",
	"Assembly",
	"Elixir",
	"Nim",
	"OpenSCAD",
	"HCL",
	"Julia",
	"Zig",
	"Markdown",
	"AutoHotkey",
	"Jinja",
	"CMake",
	"Logos",
	"OCaml",
	"Vala",
	"Pascal",
	"F#",
	"QML",
	"Wikitext",
	"Scheme",
	"Visual Basic .NET",
	"Ren'Py",
	"ASL",
	"Roff",
	"Crystal",
	"HLSL",
	"Adblock Filter List",
	"GLSL",
	"Verilog",
	"D",
	"VHDL",
	"Mustache",
	"Smarty",
	"Ada",
	"Nunjucks",
	"GAP",
	"Elm",
	"Handlebars",
	"ShaderLab",
	"AutoIt",
	"Erlang",
	"Raku",
	"Starlark",
	"Objective-C++",
	"CoffeeScript",
	"Groovy",
	"Haxe",
	"VBA",
	"Puppet",
	"Racket",
	"MATLAB",
	"Cuda",
	"Rich Text Format",
	"G-code",
	"Fennel",
	"PLpgSQL",
	"Prolog",
	"Mathematica",
	"V",
	"AsciiDoc",
	"Processing",
	"WebAssembly",
];

const input = document.getElementsByTagName("input")[0];
const queryContainer = document.getElementById("search-container");

input.addEventListener("input", () => {
	queryContainer.innerHTML = "";
	let potentialLanguageTyped = searchQueryProgrammingLanguage.filter(
		(lang) =>
			input.value.length > 1 && lang.toLocaleLowerCase().includes(input.value)
	);
	potentialLanguageTyped.forEach((language) => {
		let queryDisplay = document.createElement("h3");
		queryDisplay.innerText = language;
		queryContainer.append(queryDisplay);
	});
});
